service:
  name: nodejs-aws-be
app: products-retrieve-service
org: aws-node-cource
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-east-1
  

functions:
  first:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: post
          cors: true
      
  second:
    handler: handler.getProductById
    events:
      - http:
          method: get
          path: products/{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
