service:
  name: nodejs-aws-be
app: products-retrieve-service
org: alekseibulgakstudy
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  

functions:
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
          cors: false
      
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          method: get
          path: products/{id}
          cors: false
          request:
            parameters:
              paths:
                id: true
