service: authorization-service
app: authorization-service
org: alekseibulgakstudy

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, self:custom.region}

  environment:
    CREDENTIALS: ${env:CREDENTIALS}

custom:
  region: eu-west-1
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

plugins:
  - serverless-plugin-webpack
  - serverless-iam-roles-per-function 
  - serverless-dotenv-plugin

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer